---
title: "bootstrapping"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(p8105.datasets)

set.seed(1)
```

## Bootsrapping in SLR

```{r bootstrapping}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const %>% 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

Usual linear regression assumptions hold and one case in which they don’t

```{r}
sim_df = 
  bind_rows(const = sim_df_const, nonconst = sim_df_nonconst, .id = "data_source") 

sim_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source) 
```


```{r}
lm(y ~ x, data = sim_df_const) %>% 
  broom::tidy() #%>% 
  #knitr::kable(digits = 3)
```

```{r}
lm(y ~ x, data = sim_df_nonconst) %>% 
  broom::tidy() #%>% 
  #knitr::kable(digits = 3)
```

## Let's try use the bootstrap

```{r}
bootstrap_sample <-
  sim_df_nonconst %>%
  sample_frac(size = 1, replace = TRUE) %>%
  arrange(x)

lm(y~x, data = bootstrap_sample)
```

Let's write it as a function

```{r}
boot_sample = function(df) {
  # KEY With replacement
  sample_frac(df, replace = TRUE)
}
```

```{r}
boot_sample(sim_df_nonconst) %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")
```

```{r}
boot_straps = 
  data_frame(
    strap_number = 1:1000,
    strap_sample = rerun(1000, boot_sample(sim_df_nonconst))
  )

boot_straps
```

From here..., things are kinda the same as "always"

```{r}
boot_straps_results <-
  boot_straps %>%
  mutate(
    models = map(.x = strap_sample, ~lm(y~x, data = .x)),
    results = map(models, broom::tidy)
  ) %>%
  select(strap_number, results) %>%
  unnest(results)
```

```{r}
boot_straps_results %>%
  ggplot(aes(x = estimate)) +
  geom_histogram() +
  facet_grid(~term, scales = "free")

lm(y~x, data = sim_df_nonconst) %>%
  broom::tidy()

boot_straps_results %>%
  group_by(term) %>%
  summarize(
    se = sd(estimate)
  )
```

```{r}
sim_df_const %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(models = map(strap, ~lm(y ~ x, data = .x) ),
         results = map(models, broom::tidy)) %>% 
  select(-strap, -models) %>% 
  unnest(results) %>% 
  group_by(term) %>% 
  summarize(boot_se = sd(estimate))
```

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = room_type)) + 
  geom_point()
```

```{r}
gg_density <-
  nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  modelr::bootstrap(n = 1000) %>% 
  mutate(
    models = map(strap, ~ lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(results) %>% 
  unnest(results) %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate)) + geom_density()
```

```{r}
gg_scatter <-
  nyc_airbnb %>%
  filter(boro == "Manhattan") %>%
  ggplot(aes(x = stars, y = price)) +
  geom_point()

(gg_scatter + gg_density)
```

Not a normal ditribution



